#!/usr/bin/env python
import sys
import os
import boto3
ACCESS_ID ='xxxx'
ACCESS_KEY ='xxxx'
s3 = boto3.resource('s3',aws_access_key_id=ACCESS_ID,aws_secret_access_key=ACCESS_KEY)
bucket = s3.Bucket('fyprojj')
try:
    bucket.upload_file('abc','t.png')
    object_acl = s3.ObjectAcl('fyprojj','t.png')
    response = object_acl.put(ACL='public-read') 
    print(response)
except Exception as error:
    print(error)



